USE ecommerce_db;

-- 1. Total number of customers
SELECT COUNT(*) AS total_customers
FROM customers;


-- 2. Total number of products
SELECT COUNT(*) AS total_products
FROM products;


-- 3. Total number of orders
SELECT COUNT(*) AS total_orders
FROM orders;


-- 4. Orders by status
SELECT
    status,
    COUNT(*) AS total_orders
FROM orders
GROUP BY status;


-- 5. Products with price greater than 10000
SELECT
    product_id,
    product_name,
    category,
    price
FROM products
WHERE price > 10000
ORDER BY price DESC;


-- 6. Total quantity sold for each product
SELECT
    p.product_name,
    SUM(oi.quantity) AS total_quantity_sold
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_quantity_sold DESC;


-- 7. Revenue generated by each product
SELECT
    p.product_name,
    SUM(oi.quantity * p.price) AS revenue
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
JOIN orders o
    ON oi.order_id = o.order_id
WHERE o.status = 'Completed'
GROUP BY p.product_id, p.product_name
ORDER BY revenue DESC;


-- 8. Revenue by city
SELECT
    c.city,
    SUM(oi.quantity * p.price) AS revenue
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
JOIN orders o
    ON oi.order_id = o.order_id
JOIN customers c
    ON o.customer_id = c.customer_id
WHERE o.status = 'Completed'
GROUP BY c.city
ORDER BY revenue DESC;


-- 9. Customer-wise spending
SELECT
    c.customer_id,
    c.name,
    SUM(oi.quantity * p.price) AS total_spent
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
WHERE o.status = 'Completed'
GROUP BY c.customer_id, c.name
ORDER BY total_spent DESC;


-- 10. Monthly revenue
SELECT
    DATE_FORMAT(o.order_date, '%Y-%m') AS month,
    SUM(oi.quantity * p.price) AS revenue
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
WHERE o.status = 'Completed'
GROUP BY DATE_FORMAT(o.order_date, '%Y-%m')
ORDER BY month;